### PR TITLE
Add multiple group/channels capability

### PR DESCRIPTION
**Pull request by g5pw**
These patches add multiple channel/group bridging. Please note, this still has
room for improvement :)

Note, 806ce21 and 23044de may be because I tested it on `limnoria`, no testing
has been done on `supybot`.

### CODE REVIEW

**Comment by g5pw** [comment]
We could add the excellent `python-telegram-bot` library and use that instead of rolling our own, but that makes the plugin bulkier. Thoughts?

**Comment by g5pw** [comment]
@bhdn feel free to disregard the latest commit (4595e86)

**Comment by bhdn** [comment]
(Back from vacations)

Thanks for the work on it!

Can I only ask you to update `README.md` regarding the change in `tgChatId`?

**Comment by g5pw** [comment]
Sure, will do!

**Comment by g5pw** [comment]
I actually suggest an improvement. I added a log entry for each telegram message received without a linked IRC channel, so when creating a new association the user can just add the bot to a group and send a message. The chat ID can be extracted from the logs.

Bonus points: this works even if your bot is already in the channel (it doesn't show up in `bot_info.py` if it is)

**Comment by bhdn** [comment]
Nice idea. If you have done this change already, please push it for this PR.

**Comment by g5pw** [comment]
Pushed 😃

**Comment by g5pw** [comment]
Thanks for the merge!
By the way: at least #1, #2 and #5 should be fixed with this PR.

**Pull request merged**
